name: "Inventory"
description: "An app for keeping track of items at home"
version: "1.3.1"
slug: "inventory"
image: ghcr.io/kmayne/inventory
init: false
startup: application
boot: auto
arch:
  - aarch64
  - amd64
ports:
  3000/tcp: 3000
webui: http://[HOST]:[PORT:3000]
options:
  origins: []
schema:
  origins:
    - url
